### ISSUE TITLE
Could not select Fighter class.

### ISSUE THREAD

**Issue by BboyZeroOne** [cervinakuy/KitPvP#11]
Could not select Fighter class in class selection GUI. When clicked, console spammed some errors.

https://pastebin.com/Dm7eyng7

Please take a look, thanks!

**Comment by cervinakuy** [comment]
According to the error, it actually has to do with LuckPerms:
`Caused by: java.lang.NullPointerException: permission
at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:171) ~[?:?]`

What happens if you temporarily uninstall LuckPerms? Are you able to select the kit then? Also, is this an issue exclusive to the Fighter kit, or all kits?

**Comment by BboyZeroOne** [comment]
Its only exclusively for Fighter kit. Have not tested temporarily uninstalling LuckPerms yet

**Comment by cervinakuy** [comment]
Please do try temporarily uninstalling LuckPerms. Also, can you post a pastebin.com of your Fighter.yml? Thanks!

**Comment by BboyZeroOne** [comment]
Sorry, still have not tested but will follow up with you shortly.

**Comment by cervinakuy** [comment]
Due to inactivity and the recent bug fixes, this issue has been closed. Please contact me if you are still experiencing this problem.
