### ISSUE TITLE
Listeners Performance

### ISSUE THREAD

**Issue by LucidAPs** [cervinakuy/KitPvP#140]
The performance for some of the listeners is terrible, can you at least make some of them async so they don't run on the main thread?
![image](https://user-images.githubusercontent.com/42933023/113052781-3686af00-91b0-11eb-82bc-e3d36716f8ca.png)

**Comment by cervinakuy** [comment]
Thanks for creating this issue. Can I get your Discord? i'd like to work with you personally on this issue.

I've learned DeathListener's performance is typically bad for high player counts, mostly due to updating stats and parsing the stats.yml file each time, which I am working on a solution for (using a local database, no more text files). This is my guess for the problem in your case.

Although the other listeners don't typically have bad performance, which is why I'd like to work with you on this to identify the causes.

**Comment by cervinakuy** [comment]
Presumed resolved; stats.yml has since been removed and replaced with a SQLite database that is significantly faster. If you are still experiencing these issues, please re-open
