### ISSUE TITLE
Dropping and moving Kit Selector

### ISSUE THREAD

**Issue by SideWayy** [cervinakuy/KitPvP#142]
**Description of the bug**
Players are able to move the kit selector in there inventory and drop it on the ground

**Screenshot of /kp debug**
https://prnt.sc/118txdw

**Pastebin.com of any relevant .yml files (if applicable)**
https://pastebin.com/XCnDfMwy

**Comment by cervinakuy** [comment]
Thanks for creating this issue, but this is not a bug.

- There is no option to disable moving the kit selector or other items in a player inventory, you would have to install an external plugin to get this behavior
- The kit selector can be dropped because you disabled `PreventItemDropping` in the config.yml. If you want to prevent item dropping in a specific region, such as a spawn area, I recommend WorldGuard.
