### ISSUE TITLE
while using the bomber class the tnt does no damage to anyone 

### ISSUE THREAD

**Issue by PrivatePurple93** [cervinakuy/KitPvP#175]
**Problem**
tnt does no damage

**What I have tried**
looking in the config files menu file and abilities file and i cant find anything that would cause it to not work

**Screenshot of /kp debug**
![Screenshot (26)](https://user-images.githubusercontent.com/75870778/136579171-fbd35610-fe66-4e5d-8ef4-a090ecf4ae81.png)

**Any additional information (copy of config files, screenshots, videos, etc.)**

it wont let me copy over the files here.

**Comment by PrivatePurple93** [comment]
oh and also the return to hub watch doesnt work ive tried adding the command /warp spawn but pretty much no matter what way i add it it doesnt work

**Comment by cervinakuy** [comment]
> tnt does no damage
This is not due to my plugin. An easy way to tell this is to uninstall all other plugins except for KitPvP, and TNT will work fine. I would uninstall plugins 1-by-1 until you identify the cause

> oh and also the return to hub watch doesnt work
Please read [the wiki](https://github.com/cervinakuy/KitPvP/wiki/Common-Issues#return-to-hub-item-not-working) before posting issues in the future
