### ISSUE TITLE
Instant Damage Potion Make The Kit Unsuable

### ISSUE THREAD

**Issue by n2g7mutf8** [cervinakuy/KitPvP#191]
**Description of the bug**
After creating a kit with an instant damage potion the kit will not work.

I have created a kit with all the potion type to test it work or not [This test kit does not contain harming potion]. When i make another one with the instant damage potion the kit becomes unusable.

https://i.imgur.com/Zu7fiKj.png

Log: https://pastebin.com/DubS4si1

**Screenshot of /kp debug**
https://i.imgur.com/RzNRbrX.png

**Additional screenshots or video (if applicable)**

**Pastebin.com of any relevant .yml files (if applicable)**
https://pastebin.com/DubS4si1

the kit YAML file: https://pastebin.com/A4FwST2b
[I haven't moded the kit yml file yet! I just let it generate by use /kp create <KitName>]

**Comment by cervinakuy** [comment]
Thanks for reporting.

After looking into this issue, it actually appears to be a bug with one of the utilities used in the code. I have since posted [an issue](https://github.com/CryptoMorin/XSeries/issues/159) for that bug separately, and will close this issue once it is fixed. This will definitely be included in the next update.
