### ISSUE TITLE
A couple questions for noob

### ISSUE THREAD

**Issue by ctagliaferro** [cervinakuy/KitPvP#197]
**Problem**
1) I created an arena in my world that also has several hungergames arenas in it.  Is there a way to make it where a player has to do a join command or something in order to participate in kitpvp and then leave it to go back to the full world?
2) I cannot get the return to hub working.  I tried doing the setup in the config file, but it is on our own school local server.  Is there a tutorial to get that working?

Its a great plugin...  i appreciate all of your hard work on it.
Charlie

**What I have tried**

**Screenshot of /kp debug**

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by cervinakuy** [comment]
Thanks for reaching out.

1. As per the [installation guide](https://github.com/cervinakuy/KitPvP/wiki/Installation), KitPvP must have its own individual world. KitPvP's features are too expansive to somehow be restricted to an area of a world.
2. [Yes](https://github.com/cervinakuy/KitPvP/wiki/Common-Issues#return-to-hub-item-not-working).

I would also politely ask that you please review the content on the Wiki. I can assure you it answers 99% of most people's questions. Otherwise, please feel free to re-open this issue if necessary
