### ISSUE TITLE
Automatic scoreboard update

### ISSUE THREAD

**Issue by Maxminedigger** [cervinakuy/KitPvP#225]
**Description of the feature**
It would be a really nice feature to always have the KitPvP scoreboard showing. Since this one is quite buggy and doesn't show for new players.

**Comment by cervinakuy** [comment]
What you're experiencing is likely due to other plugins conflicting with KitPvP's built-in scoreboard.
The scoreboard is meant to be rudimentary (KitPvP is not dedicated a scoreboard plugin), so for a more advanced scoreboard experience, it is recommended to pair KitPvP with a 3rd party scoreboard plugin.

**Comment by Maxminedigger** [comment]
I have tried with and without multiple 3rd party scoreboards plugins and it does not work at all.

**Comment by cervinakuy** [comment]
Could you elaborate? Assuming you have disabled KitPvP's built-in scoreboard, a scoreboard from another plugin not working would not be caused by KitPvP.
