### ISSUE TITLE
Very high lag during kills

### ISSUE THREAD

**Issue by Spinogl** [cervinakuy/KitPvP#227]
**Description of the bug**
Every time a kill is made on the server, there's a huge lag.
If I do a timings, minecraft tells me it's from the kitpvp death event.
We've tried this in the latest version of the plugin but it doesn't fix the problem. We even have more bugs, because some things must have changed and our system no longer works.

**Screenshot of /kp debug**
![image](https://github.com/cervinakuy/KitPvP/assets/28354360/1807d6a3-c489-40e8-92db-42e9f08542a7)

**Additional screenshots or video (if applicable)**
https://timings.aikar.co/dev/?id=5b2adccb2fb44c35bd5d45ea6280aa98

**Pastebin.com of any relevant .yml files (if applicable)**
I don't know if I should send you anything.
If I have to send something, let me know and I'll send you my files.

**Comment by cervinakuy** [comment]
The timings don’t seem to provide any insight for some reason. Please comment your Discord name and I can follow-up to investigate further.On Feb 11, 2024, at 1:28 PM, Spinogl ***@***.***> wrote:﻿
Description of the bug
Every time a kill is made on the server, there's a huge lag.
If I do a timings, minecraft tells me it's from the kitpvp death event.
We've tried this in the latest version of the plugin but it doesn't fix the problem. We even have more bugs, because some things must have changed and our system no longer works.
Screenshot of /kp debug
image.png (view on web)
Additional screenshots or video (if applicable)
https://timings.aikar.co/dev/?id=5b2adccb2fb44c35bd5d45ea6280aa98
Pastebin.com of any relevant .yml files (if applicable)
I don't know if I should send you anything.
If I have to send something, let me know and I'll send you my files.

**Comment by Spinogl** [comment]
Hello,

I give you the discord of the person who manages kitpvp on my server. He will be able to answer you better than I can if you have any questions.

Discord : rozzarck

Thank you

**Comment by cervinakuy** [comment]
> I give you the discord of the person who manages kitpvp on my server
They did not follow-up so I will be closing this issue for now. Feel free to re-open if necessary.
