### ISSUE TITLE
A series of murders across different worlds (killstreaks)

### ISSUE THREAD

**Issue by akva449** [cervinakuy/KitPvP#243]
I am writing through a translator, I hope you will understand me. Can you make it possible to set up a series of murders (killstreaks) by worlds, so that, say, in one world you can make 10 murders and get 1 diamond through the team, and in another for the same 10 murders through the team, let's say you get 3 diamonds and so on

**Comment by cervinakuy** [comment]
The best solution is to use BungeeCord with separate servers, or disable KitPvP's built-in killstreaks feature and use a 3rd party killstreaks plugin with your desired functionality.

Otherwise this would start a cascading effect where other features also need to be separate across worlds (e.g. stats, scoreboard, and so on).
