### ISSUE TITLE
Changing kit abilities

### ISSUE THREAD

**Issue by akhui** [cervinakuy/KitPvP#259]
Hi there, I want to edit a kit thats alredy in the game from the start. In my case rn I want to remove the bilndness effect when using the teleportation effect from the warper kit. And i want to change that you get more abilities when killing a player. If you can help me with that i would be very happy  :) <-- me

**Comment by cervinakuy** [comment]
> I want to remove the bilndness effect when using the teleportation effect from the warper kit

Unfortunately, the built-in abilities (e.g. Warper Vanish Stars) are not customizable beyond what is already included in the abilities.yml at this time.

> i want to change that you get more abilities when killing a player

This isn't possible at the moment either; however, you can set a cooldown for each ability so that players never run out, [as explained in the wiki](https://github.com/cervinakuy/KitPvP/wiki/Creating-an-ability).
