### ISSUE TITLE
Soups sometimes doesn't work when you refill from your inventory to your hotbar.

### ISSUE THREAD

**Issue by tommyteschner** [cervinakuy/KitPvP#43]
**Description of the bug**
Soups (sometimes not always) do not work when you refill from your inventory to your hotbar and it makes the game unplayable because you cannot regen.

**Screenshot of /kp debug**
https://i.imgur.com/7C3MsRF.png and https://i.imgur.com/sMzHocA.png

**Additional screenshots or video (if applicable)**

**Pastebin.com of any relevant .yml files (if applicable)**

**Comment by din0s** [comment]
A followup on this, we were able to reproduce the issue and it seems to me like sometimes the player will spawn with a de-synchronized inventory. What this means is that no matter how they reorder their items, the server will never get updated with the new inventory.

You can confirm that the issue is linked to inventory going out of sync between client & server, since other players don't see the user holding anything in their hand, even though in first person it looks like they have a bowl of soup.

**Comment by cervinakuy** [comment]
This does not seem to be a problem with my plugin. If you can prove otherwise, please either re-open this issue or open a new one entirely. My plugin doesn't do any special handling of inventory vs hotbar items, so this leads me to believe it's either an issue with running an outdated server version or a conflict with a different plugin.
