### ISSUE TITLE
KitPvP enchant 

### ISSUE THREAD

**Issue by doragoma** [cervinakuy/KitPvP#51]
Kit settings

I use interpretation software. I'm sorry if there are any quirks.
I'm using KITPVP, but I don't know how to set up the enchant and I looked at the wiki, but I didn't understand it just because it says "enchant".
If possible, I'd like an example of a kit with enchanted settings.

**Comment by cervinakuy** [comment]
Hi there, [here](https://github.com/cervinakuy/KitPvP/blob/0fa57e528152e73677eed8aff2ca0cdb0d9a0c7b/src/main/resources/kits/Example.yml#L36) is an example of an enchantment item from the Example kit. The reason there is no documentation for this is because enchantments are automatically saved when you create a kit using /kp create. I _highly_ recommend that you use this command too instead of manually editing and creating a kit file.

Please let me know if you have any other questions. If not, I will close this issue in a few days and assume your problem is now solved.
