### ISSUE TITLE
Am I able to connect this kitpvp plugin with buycraft? 

### ISSUE THREAD

**Issue by Micronova129** [cervinakuy/KitPvP#77]
I am wonder if I can add kits behind a paywall and in order to unlock them they have to buy via my buycraft page. If not are there any other plugins that do that?

**Comment by cervinakuy** [comment]
Yes, this would be possible to do with my plugin. Using Buycraft you give the players a specific permissions upon purchase (in this case kit permissions).

However, it may be important to note that doing so is against the [EULA](https://account.mojang.com/documents/minecraft_eula).

Please feel free to re-open this issue if you have any further questions, otherwise I will leave you with [this tutorial regarding commands](https://docs.tebex.io/store/command-management/an-introduction-to-commands) using Buycraft (Tebex).

Thanks!
